### ISSUE TITLE
Compile butt-client binary as part of this npm package

### ISSUE THREAD

**Issue by hammady** [bitfocus/companion-module-danielnoethen-butt#3]
Currently the path to butt/butt-client binary is required to be installed separately on the same machine running Companion and its path is provided via the connection configuration.
Consider compiling it as part of this npm package.

**Comment by krocheck** [comment]
@hammady this will not be possible since `butt` is under a `GNU GPLv2` license.  That is not compatible with our `MIT` license.

**Comment by hammady** [comment]
@krocheck that's great to know!
